include:
  - ./docker/postgres/postgres.yml
  - ./docker/keydb/keydb.yml
  - ./docker/minio/minio.yml
  - ./docker/mailhog/mailhog.yml
  - ./docker/directus/directus.yml
  - ./docker/backend/backend.yml